services:
  db:
    image: postgres:15
    container_name: us_politicians_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: us_politicians_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: us_politicians_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
